# Week 3 - Scratch and Quiz

RS25032023

In [1]:
import numpy as np

## Scratch

In [3]:
A = np.array([
    [5, 2], 
    [1, 2]])
print(A)

[[5 2]
 [1 2]]


In [4]:
print(np.linalg.inv(A))

[[ 0.25  -0.25 ]
 [-0.125  0.625]]


In [6]:
# This won't work as the matrix is singular.
#A = np.array([
#    [1, 1], 
#    [2, 2]])
#print(np.linalg.inv(A))

## Quiz

In [10]:
# 1.
u = np.array([1, 0, 7])
v = np.array([0, -1, 2])

$d = \sqrt{<u - v, u - v>}$

In [12]:
print((u-v) @ (u - v))

27


In [18]:
# 2.
u = np.array([1, 0, -3])
v = np.array([-1, 0, -3])

print(u - v)

[2 0 0]


In [17]:
print(np.linalg.norm(u+v))

6.0


In [27]:
u = np.array([-1, 5, 2])
v = np.array([-3, 6, -4])
print(u@v)

25


In [28]:
A = np.array([
    [2, -1], 
    [3, -3]])
B = np.array([
    [5, -2], 
    [0, 1]])
print(A*B)


[[10  2]
 [ 0 -3]]
