# Week 4 scratch

RS25032023

In [32]:
import numpy as np
import scipy as sc

In [2]:
A = np.array([
    [0.4, -0.2], 
    [-0.2, 0.6]])

print(np.linalg.det(A))

0.2


In [ ]:
A = np.array([
    [0.4, -0.2], 
    [-0.2, 0.6]])

print(np.linalg.det(A))

## Quiz 1

In [23]:
# 1.  

W = np.array([
    [1, 2, -1], 
    [1, 0, 1], 
    [0, 1, 0]])
print(np.linalg.det(W))


-2.0


In [25]:
# 2.

print(np.linalg.inv(W))

[[ 0.5  0.5 -1. ]
 [-0.  -0.   1. ]
 [-0.5  0.5  1. ]]


In [26]:
# 3.

print(np.linalg.inv(np.eye(3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Non-singular

In [14]:
b = np.array([5, -2, 0])
print(b)

[ 5 -2  0]


In [15]:
y = W @ b
print(y)

[ 1  5 -2]


In [17]:
print(np.array([3, 1, -7]) @ np.array([2, 2, 0]))

8


In [18]:
A = np.array([
    [5, 2, 3], 
    [-1, -3, 2], 
    [0, 1, -1]])
B = np.array([
    [1, 0, -4], 
    [2, 1, 0], 
    [8, -1, 0]])
print(A @ B)

[[ 33  -1 -20]
 [  9  -5   4]
 [ -6   2   0]]


In [21]:
print(np.linalg.det(A @ B))

1.782816318816259e-13


## Eigenvectors & -values

In [35]:
w, v = sc.linalg.eig(np.array([[9, 4], [4, 3]]))
print(w)
print(v)

[11.+0.j  1.+0.j]
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


In [36]:
w, v = sc.linalg.eig(np.array([[2, 1], [0, 3]]))
print(w)
print(v)

[2.+0.j 3.+0.j]
[[1.         0.70710678]
 [0.         0.70710678]]


## Quiz 2

1. and 2. Via Wolfram Alpha: eigenvectors and eigenvalues of [[2, 1], [-3, 6]]

det([[2, 1], [-3, 6]] - l*IdentityMatrix[2]) = 0

In [39]:
# 3.
sc.linalg.eig(np.eye(3))


(array([1.+0.j, 1.+0.j, 1.+0.j]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))


4. via Wolfram Alpha: eigenvectors and eigenvalues of [[1, 2], [0, 4]]

7. via Wolfram Alpha: eigenvectors and eigenvalues of [[2, 0, 0], [1, 2, 1], [-1, 0, 1]]

8. via Wolfram Alpha: det([[3, 1, -2], [4, 0, 1], [2, 1, -1]] - l*IdentityMatrix[3]) = 0

9. via Wolfram Alpha: eigenvectors and eigenvalues of [[1, 2], [0, 4]]^-1