# Week 2 Quiz - Scribble


In [2]:
import numpy as np

In [3]:
# Define the matrix for the system.

A = np.array([
        [7, 5, 3],
        [3, 2, 5],
        [1, 2, 1]
    ], dtype=np.dtype(float))

b = np.array([120, 70, 20], dtype=np.dtype(float))

In [6]:
print(A)
print(b.reshape(3, 1))

[[7. 5. 3.]
 [3. 2. 5.]
 [1. 2. 1.]]
[[120.]
 [ 70.]
 [ 20.]]


In [7]:
# Some functions.

def MultiplyRow(M, row_num, row_num_multiple):
    # .copy() function is required here to keep the original matrix without any changes
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] = row_num_1_multiple * M_new[row_num_1] + M_new[row_num_2]
    return M_new

def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

In [15]:
x = np.linalg.solve(A, b)
with np.printoptions(precision=2, suppress=True):
    print(f"{x=}")

x=array([15.,  0.,  5.])


In [19]:
d = np.linalg.det(A)

print(f"{d=:.2f}")

d=-34.00
